#ECOS_OUT_PATH=$(FP_BASE)/$(OUT_ECOS_KERNEL)
ECOS_OUT_PATH=$(PWD)/output
L7_CPU=raptor
TARGET=ecos-2.0--$(L7_CPU)
ECOS_REPOSITORY=$(PWD)
ECOS_BUILD_OUTPUT_DIR = $(ECOS_OUT_PATH)
ECOS_BUILD_DIR := $(ECOS_BUILD_OUTPUT_DIR)/$(TARGET)/build
ECOS_INSTALL_DIR := $(ECOS_BUILD_OUTPUT_DIR)/$(TARGET)/install
ECOS_CONFIG_FILE := mips_$(L7_CPU).ecc
ECOSKERNEL_INSTALL_DIR = $(ECOS_INSTALL_DIR)
export $(ECOSKERNEL_INSTALL_DIR)

PKGID   := ECOS_KERNEL
PKGNAME := $(ROOT_$(PKGID))

ifeq (verbose,$(CMD_DISPLAY_MODE))
SILENT_MODE_FLAG :=
else
SILENT_MODE_FLAG := -s
endif

.PHONY: all
bldlib: $(TARGET)
clean: clean-ecos

$(TARGET):  $(ECOS_BUILD_DIR)/makefile ecoslib

include $(ECOS_REPOSITORY)/Makefile.common
